### PR TITLE
Update to EEG data 

### PR DESCRIPTION
**Pull request by marklescroart**
… in /data/shared/cogneuro88/eeg/ to add epfl_p300/ directory

Summary
-------
Adds several folders of EEG data in the directory above. Within /data/shared/cogneuro88/eeg/epfl_p300/ should be:

subject8/
    /session1
    /session2
    /session3
    /session4

How to test
-------
Check for above paths.

### CODE REVIEW

**Comment by gunjanbaid** [comment]
Working on the updates now.

**Review by gunjanbaid — APPROVED** [review]
Working on adding changes now.

**Comment by gunjanbaid** [comment]
Hi @marklescroart, does the commit contain the right URL? I tried accessing [https://www.dropbox.com/s/4f0ek79ytxwcgwx/cogneuro88data.tar.gz](https://www.dropbox.com/s/4f0ek79ytxwcgwx/cogneuro88data.tar.gz) but the file doesn't seem to have finished uploading yet.

**Comment by marklescroart** [comment]
Ah nuts, I closed my laptop before the file had finished uploading. It's going again now, will take a bit more time (slow connection at home). Will post again when it's up. Sorry about that!

**Comment by gunjanbaid** [comment]
Sounds good!

**Comment by marklescroart** [comment]
Try now! Should be up.

**Comment by marklescroart** [comment]
Has my update been used to update datahub-dev yet? Looks like no folders were created at all in /data/shared/cogneuro88/ - is that because of the attempt with the faulty file?

**Comment by marklescroart** [comment]
Looks like that was a yes - it's up now after a little down time with correct folders in place! All looks great, can we please get this pushed to datahub.berkeley.edu? Thanks for always excellent support!

**Comment by gunjanbaid** [comment]
There was a mistake on my end in the initial update, hence why there was no data on dev. It should all be there now! I will push this to datahub.berkeley.edu now. No problem! :)

**Comment by gunjanbaid** [comment]
Data is now on datahub.berkeley.edu!

**Pull request merged**
