### PR TITLE
[WIP] Port JHub image to k8s

### LINKED ISSUE #4: Port JHub image to k8s
At the moment, our JupyterHub image (https://github.com/data-8/jupyterhub) is not configured for use with k8s. We'll port that over.

### PR DESCRIPTION
**Pull request by derrickmar**
Closes #4

### CODE REVIEW

**Comment by SamLau95** [comment]
Looks like you put files in a folder called `jupyterhub-k8s-hub`? That should just be the `hub` folder (you should just change the files that already exist). Sorry about the confusion there.

**Comment by derrickmar** [comment]
O yeah no confusion haha. I know that. Just wanted to create my own directory for now because the Makefile isn't working. So I'm pushing to my own docker image https://hub.docker.com/r/derrickmar24/data8-jhub/

**Comment by derrickmar** [comment]
I'll move it back to hub when its ready

**Comment by derrickmar** [comment]
@SamLau95 almost working... Another bug that seems to have randomly appeared. When you try to launch a notebook (or add a file) there's this error. 

screenshot 2016-11-09 21 02 25

I haven't really changed anything since our meeting on Monday (other than deleting comments/cleaning up) so a bit confused,

**Comment by derrickmar** [comment]
Closing because using branch ds8-jhub-from-scratch

**Pull request closed without merging**
